"""initial schema

Revision ID: d1e8abcaa22c
Revises: 
Create Date: 2026-09-10 08:49:43.118914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e8abcaa22c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('field_changed', sa.String(), nullable=True),
    sa.Column('previous_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_firm_id'), 'audit_log', ['firm_id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=False),
    sa.Column('normalized_description', sa.String(), nullable=False),
    sa.Column('corrected_ledger_head', sa.String(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_firm_id'), 'corrections', ['firm_id'], unique=False)
    op.create_index(op.f('ix_corrections_normalized_description'), 'corrections', ['normalized_description'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('used_ocr', sa.Boolean(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('gstin_vendor', sa.String(), nullable=True),
    sa.Column('gstin_customer', sa.String(), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=True),
    sa.Column('cgst', sa.Float(), nullable=True),
    sa.Column('sgst', sa.Float(), nullable=True),
    sa.Column('igst', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_firm_id'), 'invoices', ['firm_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('used_ocr', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_firm_id'), 'statements', ['firm_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firm_id'), 'users', ['firm_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('total_payments', sa.Float(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('average_payment', sa.Float(), nullable=True),
    sa.Column('highest_payment', sa.Float(), nullable=True),
    sa.Column('lowest_payment', sa.Float(), nullable=True),
    sa.Column('first_payment_date', sa.String(), nullable=True),
    sa.Column('last_payment_date', sa.String(), nullable=True),
    sa.Column('is_new_vendor', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_reasons', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_firm_id'), 'vendors', ['firm_id'], unique=False)
    op.create_index(op.f('ix_vendors_normalized_name'), 'vendors', ['normalized_name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('statement_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_statement_id'), 'jobs', ['statement_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statement_id', sa.String(), nullable=False),
    sa.Column('txn_date', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('txn_type', sa.String(), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('predicted_ledger_head', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classification_method', sa.String(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_reason', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_reasons', sa.Text(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=True),
    sa.Column('matched_invoice_ref', sa.String(), nullable=True),
    sa.Column('corrected_ledger_head', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_is_anomaly'), 'transactions', ['is_anomaly'], unique=False)
    op.create_index(op.f('ix_transactions_predicted_ledger_head'), 'transactions', ['predicted_ledger_head'], unique=False)
    op.create_index(op.f('ix_transactions_risk_score'), 'transactions', ['risk_score'], unique=False)
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_risk_score'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_predicted_ledger_head'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_anomaly'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_jobs_statement_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_vendors_normalized_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_firm_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_firm_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_statements_firm_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_firm_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_corrections_normalized_description'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_firm_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_audit_log_firm_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('firms')
    # ### end Alembic commands ###
